name: Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install x86_64-w64-mingw32-gcc
        run: |
          apt update
          apt install -y gcc-mingw-w64-x86-64

      - name: Install Rust nightly with x86_64-pc-windows-gnu target
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --target x86_64-pc-windows-gnu,x86_64-unknown-linux-gnu --profile minimal
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH          

      - uses: actions/checkout@master

      - name: Compile Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu          

      - uses: akkuman/gitea-release-action@v1
        with:
          name: Rolling release
          body: Текущая версия из ветки `master`
          prerelease: true
          files: |
            target/x86_64-pc-windows-gnu/release/monitor-test-pattern-generator.exe
